version: '2'
services: 
    django: 
        container_name: django_server
        build:
            context: .
            dockerfile: Dockerfile
        image: docker_tutorial_django
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        stdin_open: true
        tty: true
        volumes: 
            - .:/app
        ports: 
            - "8080:80"
